name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 18を強制
          cache: 'npm'       # キャッシュを有効化（後でクリア）

      - name: Remove default Node.js
        run: |
          sudo apt-get update
          sudo apt-get remove -y nodejs
          sudo apt-get remove -y npm
          sudo rm -rf /usr/local/bin/node
          sudo rm -rf /usr/local/bin/npm
          sudo rm -rf /usr/local/lib/node_modules

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 再度18をインストール

      - name: Install dependencies
        run: |
          npm install -g firebase-tools@latest
          cd functions
          npm install

      - name: Deploy to Firebase
        run: firebase deploy --only "hosting,functions"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}